# Generated by Django 5.1.5 on 2025-01-21 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Сообщения')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=300, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Дата обращения')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='accounts_app.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Обращения',
                'verbose_name_plural': 'Обращения',
                'db_table': 'appeals',
            },
        ),
    ]
