# Generated by Django 5.1.5 on 2025-01-27 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports_files', verbose_name='Файл')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('watched_date', models.DateTimeField(blank=True, null=True)),
                ('read_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Отправлен'), (2, 'Просмотрена страница'), (3, 'Прочитан документ'), (4, 'Выполнен')], default=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_app.organization', verbose_name='Организация')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
            },
        ),
    ]
