# Generated by Django 5.1.5 on 2025-03-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.TextField(unique=True, verbose_name='Наименование'),
        ),
    ]
