# Generated by Django 5.1.5 on 2025-06-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_alter_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(unique=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(max_length=19, verbose_name='Мобильный номер'),
        ),
    ]
