# Generated by Django 5.1.5 on 2026-08-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0003_alter_organization_name_alter_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='org_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
