# Generated by Django 5.1.5 on 2025-11-01 06:39

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news_app', '0014_alter_news_cover_alter_newsgalleryitem_file_news_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=70, null=True)),
                ('crypto_npa', models.ManyToManyField(blank=True, null=True, to='news_app.notificationnpa')),
            ],
            options={
                'verbose_name': 'СЗИ и ЭП',
                'verbose_name_plural': 'СЗИ и ЭП',
                'db_table': 'CryptoProvider',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CryptoProviderTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='szi.cryptoprovider')),
            ],
            options={
                'verbose_name': 'СЗИ и ЭП Translation',
                'db_table': 'CryptoProvider_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
