# Generated by Django 5.1.5 on 2025-11-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szi', '0002_npalinks_cryptoprovider_npa_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptoprovider',
            name='npa_links',
        ),
        migrations.AddField(
            model_name='cryptoprovidertranslation',
            name='npa_links',
            field=models.ManyToManyField(blank=True, null=True, to='szi.npalinks'),
        ),
    ]
