# Generated by Django 5.1.5 on 2025-11-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szi', '0003_remove_cryptoprovider_npa_links_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptoprovidertranslation',
            name='npa_links',
        ),
        migrations.RemoveField(
            model_name='npalinks',
            name='link',
        ),
        migrations.AddField(
            model_name='cryptoprovider',
            name='npa_links',
            field=models.ManyToManyField(blank=True, null=True, to='szi.npalinks'),
        ),
        migrations.AddField(
            model_name='npalinkstranslation',
            name='link',
            field=models.URLField(max_length=255, null=True, verbose_name='Ссылка'),
        ),
    ]
