# Generated by Django 5.1.5 on 2025-12-30 04:04

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szi', '0004_remove_cryptoprovidertranslation_npa_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=120, verbose_name='Индекс')),
                ('address', models.CharField(max_length=155, verbose_name='Адресс')),
                ('phone', models.CharField(max_length=19, verbose_name='Мобильный номер')),
            ],
            options={
                'verbose_name': 'Заявитель',
                'verbose_name_plural': 'Заявители',
            },
        ),
        migrations.CreateModel(
            name='EncryptionTools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('applicant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='szi.applicant')),
                ('npa_links', models.ManyToManyField(to='szi.npalinks', verbose_name='Наименования документов, требованиям которых соответсвует СЗИ')),
            ],
            options={
                'verbose_name': 'Средства сертификации',
                'verbose_name_plural': 'Средства сертификации',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='EncryptionToolsTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=125, verbose_name='Наименование средства(шифр)')),
                ('components', models.CharField(max_length=100, verbose_name='Схема сертификации, кол-во СЗИ')),
                ('testing_lab', models.CharField(max_length=125, verbose_name='Испытательная лаборатория')),
                ('finish_info', models.TextField(blank=True, null=True, verbose_name='Информация об окончании срока тех поддержки')),
                ('add_date', models.CharField(max_length=80, verbose_name='Дата добавления средства')),
                ('validity_period', models.CharField(max_length=80, verbose_name='Срок действия')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='szi.encryptiontools')),
            ],
            options={
                'verbose_name': 'Средства сертификации Translation',
                'db_table': 'szi_encryptiontools_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
