# Generated by Django 5.1.5 on 2026-03-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szi', '0005_applicant_encryptiontools_applicanttranslation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encryptiontoolstranslation',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Наименование средства(шифр)'),
        ),
    ]
