# Generated by Django 5.1.5 on 2025-12-30 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('szi', '0005_applicant_encryptiontools_encryptiontoolstranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='encryptiontoolstranslation',
            name='number',
            field=models.CharField(default='Test', max_length=125, verbose_name='Номер сертификата'),
            preserve_default=False,
        ),
    ]
