# Generated by Django 5.1.5 on 2025-01-21 05:51

import django.db.models.deletion
import parler.fields
import parler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoPages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(max_length=255, verbose_name='Название страницы')),
            ],
            options={
                'verbose_name': 'Сео страница',
                'verbose_name_plural': 'Сео страница',
                'db_table': 'seo_pages',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SeoPagesTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('meta_tag_title', models.CharField(max_length=255, verbose_name='Заголовок страницы')),
                ('meta_tag_keywords', models.TextField(verbose_name='Ключевые слова')),
                ('meta_tag_description', models.TextField(verbose_name='Описание страницы')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main_app.seopages')),
            ],
            options={
                'verbose_name': 'Сео страница Translation',
                'db_table': 'seo_pages_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
