# Generated by Django 5.1.5 on 2025-03-25 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_chartlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chartlink',
            options={'verbose_name': 'Граффик', 'verbose_name_plural': 'Граффики'},
        ),
    ]
