# Generated by Django 5.1.5 on 2025-03-06 11:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание сообщения')),
                ('name', models.CharField(max_length=150, verbose_name='ФИО')),
                ('file', models.FileField(blank=True, null=True, upload_to='Messages/2025-03-06', verbose_name='Файл')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone_number', models.CharField(blank=True, max_length=19, null=True, validators=[django.core.validators.RegexValidator('\\^+\\d+$', 'Only numeric characters are allowed.'), django.core.validators.MaxLengthValidator], verbose_name='Мобильный номер')),
                ('host_ip', models.TextField(blank=True, null=True, verbose_name='IP')),
                ('domain_name', models.TextField(blank=True, null=True, verbose_name='Domain Name')),
                ('hash', models.TextField(blank=True, null=True, verbose_name='Hash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сообщение об инциденте',
                'verbose_name_plural': 'Сообщения об инцидентах',
                'db_table': 'Messages',
            },
        ),
    ]
