# Generated by Django 5.1.5 on 2025-06-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0005_alter_messages_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Messages/2025-06-22', verbose_name='Файл'),
        ),
    ]
