# Generated by Django 5.1.5 on 2025-02-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0006_alter_messages_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'verbose_name': 'Сообщение об инциденте', 'verbose_name_plural': 'Сообщения об инцидентах'},
        ),
        migrations.RemoveField(
            model_name='messages',
            name='status',
        ),
        migrations.AlterField(
            model_name='messages',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Messages/2025-02-24', verbose_name='Файл'),
        ),
    ]
