# Generated by Django 5.1.5 on 2025-12-04 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0010_alter_messages_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='phone_number',
            field=models.CharField(blank=True, max_length=19, null=True, validators=[django.core.validators.MaxLengthValidator], verbose_name='Мобильный номер'),
        ),
    ]
