# Generated by Django 5.1.5 on 2025-12-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0011_alter_messages_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Messages/2025-12-27', verbose_name='Файл'),
        ),
    ]
