# Generated by Django 5.1.5 on 2026-08-10 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0014_alter_messages_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Messages/2026-08-10', verbose_name='Файл'),
        ),
    ]
