# Generated by Django 5.1.5 on 2025-05-13 11:52

import django.db.models.deletion
import parler.fields
import parler.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_security_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CyberIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Инцидент кибербезопасности',
                'verbose_name_plural': 'Инциденты кибербезопаснсти',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='CyberIncidentTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('description', tinymce.models.HTMLField(verbose_name='Описание')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='cyber_security_app.cyberincident')),
            ],
            options={
                'verbose_name': 'Инцидент кибербезопасности Translation',
                'db_table': 'cyber_security_app_cyberincident_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
