# Generated by Django 5.1.5 on 2025-02-20 11:19

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationnpa',
            name='lang',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ru'), (2, 'en'), (3, 'ky')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='cover',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='News/2025-02-20', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='newsgalleryitem',
            name='file_news',
            field=models.FileField(blank=True, null=True, upload_to='News_gallery/2025-02-20', verbose_name='Файлы новостей'),
        ),
        migrations.AlterField(
            model_name='notificationnpatranslation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='laws/2025-02-20'),
        ),
    ]
