# Generated by Django 5.1.5 on 2025-01-27 04:20

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_alter_news_cover_alter_newsgalleryitem_file_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cover',
            field=django_resized.forms.ResizedImageField(crop=['middle', 'center'], force_format='WEBP', keep_meta=True, null=True, quality=80, scale=None, size=[1920, 1080], upload_to='News/2025-01-27', verbose_name='Обложка'),
        ),
        migrations.AlterField(
            model_name='newsgalleryitem',
            name='file_news',
            field=models.FileField(blank=True, null=True, upload_to='News_gallery/2025-01-27', verbose_name='Файлы новостей'),
        ),
    ]
