# Generated by Django 5.1.5 on 2025-02-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_notificationnpa_lang_alter_news_cover_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationnpa',
            name='lang',
        ),
    ]
